/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEditKeyModal: typeof import('./src/components/keys/AddEditKeyModal.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    BentoCard: typeof import('./src/components/common/BentoCard.vue')['default']
    GlobalNotification: typeof import('./src/components/common/GlobalNotification.vue')['default']
    QuickActions: typeof import('./src/components/dashboard/QuickActions.vue')['default']
    RecentActivity: typeof import('./src/components/dashboard/RecentActivity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsGrid: typeof import('./src/components/dashboard/StatsGrid.vue')['default']
    SystemStatus: typeof import('./src/components/dashboard/SystemStatus.vue')['default']
    ViewSwitcher: typeof import('./src/components/ViewSwitcher.vue')['default']
    WelcomeSection: typeof import('./src/components/dashboard/WelcomeSection.vue')['default']
  }
}
